# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
                ('file_name', models.CharField(max_length=30)),
                ('pronunciation', models.CharField(max_length=30)),
                ('pos', models.CharField(max_length=30)),
                ('land_of_origin', models.CharField(max_length=30)),
                ('additional_info', models.CharField(max_length=30)),
                ('added_by', models.CharField(max_length=30)),
                ('created_by', models.CharField(max_length=30)),
                ('spellbee_type', models.CharField(choices=[('JSB', 'JSB'), ('SSB', 'SSB')], max_length=30)),
                ('phase', models.CharField(choices=[('Phase 1', 'Phase 1'), ('Phase 2', 'Phase 2')], max_length=30)),
                ('year', models.CharField(max_length=30)),
            ],
        ),
    ]
