# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-30 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audioinput_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=10)),
                ('dob', models.DateField()),
                ('class_name', models.CharField(max_length=30)),
                ('spellbee_type', models.CharField(choices=[('Phase 1', 'Phase 1'), ('Phase 2', 'Phase 2')], max_length=30)),
                ('phase', models.CharField(max_length=30)),
                ('school_name', models.CharField(max_length=50)),
            ],
        ),
    ]
