# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_phaseresults_questionresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_type', models.CharField(max_length=20)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AudioInput')),
            ],
        ),
        migrations.RemoveField(
            model_name='questionresult',
            name='phase_type',
        ),
        migrations.RemoveField(
            model_name='questionresult',
            name='word',
        ),
        migrations.AddField(
            model_name='questionresult',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionresult',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PhaseQuestions'),
        ),
    ]
