# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-01 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191001_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase2Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.CharField(max_length=10)),
                ('wrong_answers', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Student')),
            ],
        ),
    ]
