# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-07 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_audioinput_difficulty_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioinput',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], default='Easy', max_length=30),
        ),
    ]
