# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-11 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20191009_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioinput',
            name='file_name_origin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='audioinput',
            name='full_name_complete',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='audioinput',
            name='full_name_sentence',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
