# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-14 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20191011_0921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audioinput',
            old_name='full_name_complete',
            new_name='file_name_complete',
        ),
        migrations.RenameField(
            model_name='audioinput',
            old_name='full_name_sentence',
            new_name='file_name_sentence',
        ),
        migrations.AddField(
            model_name='audioinput',
            name='fill_name_definition',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
