# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191014_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioinput',
            name='added_by',
        ),
        migrations.AddField(
            model_name='audioinput',
            name='sentence',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='audioinput',
            name='additional_info',
            field=models.CharField(max_length=3000),
        ),
    ]
