# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191015_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowIntroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True)),
            ],
        ),
    ]
